name: Pocketbase

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['pocketbase/**']
  schedule:
    # Runs "At 01:00." (see https://crontab.guru)
    - cron: '0 1 * * *'

jobs:
  check:
    uses: AdoboTec/reusable-workflows/.github/workflows/compare_github_docker_tags.yml@main
    with:
      repo_github: pocketbase/pocketbase
      repo_docker: chaudric/pocketbase

  docker_hub:
    uses:  AdoboTec/reusable-workflows/.github/workflows/image_build_push.yml@main
    needs: check
    if: ${{ !contains(needs.check.outputs.docker_version, needs.check.outputs.repo_version) }}
    with:
      directory: .
      image_name: pocketbase
      image_version: ${{ needs.check.outputs.repo_version }}
      docker_owner: adobotec
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}