name: Pocketbase

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['pocketbase/**']
  # schedule:
  #   # Runs "At minute 15 past every 3rd hour." (see https://crontab.guru)
  #   - cron: '15 */3 * * *'

jobs:
  check:
    uses: AdoboTec/reusable-workflows/.github/workflows/compare_github_docker_tags.yml@main
    with:
      repo_github: pocketbase/pocketbase
      repo_docker: ${{ github.repository }}

  docker_hub:
    uses:  AdoboTec/reusable-workflows/.github/workflows/image_build_push.yml@main
    needs: check
    if: ${{ !contains(needs.check.outputs.docker_version, needs.check.outputs.repo_version) && needs.check.outputs.repo_version != 'null' }}
    with:
      directory: .
      image_version: ${{ needs.check.outputs.repo_version }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  docker_test:
    needs: docker_hub
    runs-on: [ ubuntu-latest ]
    container: curlimages/curl

    services:
      pocketbase:
        image: ghcr.io/adobotec/docker-pocketbase:latest

    steps:
      - name: Check api/health
        run: curl -X GET -f -LI http://pocketbase:8080/api/health